apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-blue
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
      matchLabels:
        app: capstone
        version: blue
  template:
    metadata:
      labels:
        app: capstone
        version: blue
    spec:
      containers:
        - name: capstone
          image: docker.io/navalkishorupadhyay/devops_capstone_blue
          imagePullPolicy: Always
          ports:
            - containerPort: 80
